### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rbx-dom#13]
I am currently getting this error:

`Message("don\'t know how to decode this prop type")`

This is a pretty bad error, it doesn't even say the property type.

**Comment by LPGhatguy** [comment]
Error messages should probably be redone to use a `String` or `Cow<'static, str>` under the hood so that we can generate better errors.

**Comment by LPGhatguy** [comment]
This is done for `rbx_xml`, and there's a followup issue for rbx_binary: #48.
