### ISSUE TITLE
rbx_xml name mapping for Fire

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rbx-dom#14]
For `Fire`, `Size` serializes as `size_xml`, and another property I can't remember has a weird name too. Need to add an XML<->Canonical name mapping for `Fire`.

**Comment by Kampfkarren** [comment]
That means this needs to be changed to be class specific instead of broad property names:

https://github.com/LPGhatguy/rbx-dom/blob/9700f1417e2de7f119fc1701138e6a370e84f744/rbx_xml/src/reflection.rs#L13

**Comment by LPGhatguy** [comment]
I'll probably move it into the `rbx_reflection` crate eventually, too!

**Comment by LPGhatguy** [comment]
Foundation for this is in now that #28 is around. I'm currently experimenting with porting `rbx_xml` over to use `rbx_reflection` under the hood, which will be known as reflection-guided serialization.
