### ISSUE TITLE
Support for INF/NAN in rbx_xml

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rbx-dom#33]
BillboardGui's MaxDistance is INF and this presumably causes issues. I assume this happens for nan too.

**Comment by Reshiram110** [comment]
More specific info : This issue occurs on line 27 of this [xml model file](https://hastebin.com/raw/aqupomokoh), `<float name="MaxDistance">INF</float>`

The output of rojo is:
```
[ERROR rojo] Malformed rbxmx model: ParseFloatError(ParseFloatError { kind: Invalid }) in path <path to xml model file>
```

**Comment by LPGhatguy** [comment]
Thanks for the issue!

I'm guessing that I'll also have to handle serialization of negative infinity and NaN.
