### ISSUE TITLE
Conversions from BrickColor to Color3

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rbx-dom#45]
This should be pretty straightforward in the context of `RbxValue::try_convert_ref`. I'm not sure if we want to bother trying to go the other direction since it's lossy.

**Comment by Kampfkarren** [comment]
```
> c = BrickColor.Red().Color print(typeof(c), c)
Color3 0.768628, 0.156863, 0.109804
```

**Comment by LPGhatguy** [comment]
Yeah, we'll probably want to go through with a script and output some formatted data we can chunk in. That seems like our ticket!
