### ISSUE TITLE
INF/NAN doesn't work for Vector2

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rbx-dom#53]
Despite #33, INF/NAN does not work in Vector2 (and others with the same thought process) likely because they use the direct float parse methods instead of the one used for Float32/Float64.

https://github.com/LPGhatguy/rbx-dom/blob/master/rbx_xml/src/types/vectors.rs#L37

**Comment by LPGhatguy** [comment]
Fixed by #62!
