### ISSUE TITLE
SharedString in rbx_dom_weak

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rbx-dom#60]
We should be able to create a shared string dictionary per tree. When moving instances between trees, it should be possible to add entries from the shared string table.

I'm not super sure how the entries should be cleaned up, especially since it's possible for consumers of rbx_dom_weak to mutate properties arbitrarily. Maybe that'll be left up to consumers? Maybe there could be some ref-counting nonsense?

**Comment by Kampfkarren** [comment]
Arc<Mutex<String>>?

**Comment by LPGhatguy** [comment]
The `Mutex` shouldn't be useful because I'm pretty sure the buffers are immutable -- to get a new buffer, you need to change the hash of the contents I think!
